/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FailedRouteImport } from './routes/failed'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ApiPublicCreatePaymentRouteImport } from './routes/api/public/create-payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FailedRoute = FailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreatePaymentRoute = ApiPublicCreatePaymentRouteImport.update({
  id: '/api/public/create-payment',
  path: '/api/public/create-payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/failed': typeof FailedRoute
  '/success': typeof SuccessRoute
  '/api/public/create-payment': typeof ApiPublicCreatePaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/failed': typeof FailedRoute
  '/success': typeof SuccessRoute
  '/api/public/create-payment': typeof ApiPublicCreatePaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/failed': typeof FailedRoute
  '/success': typeof SuccessRoute
  '/api/public/create-payment': typeof ApiPublicCreatePaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/checkout' | '/failed' | '/success' | '/api/public/create-payment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/failed' | '/success' | '/api/public/create-payment'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/failed'
    | '/success'
    | '/api/public/create-payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  FailedRoute: typeof FailedRoute
  SuccessRoute: typeof SuccessRoute
  ApiPublicCreatePaymentRoute: typeof ApiPublicCreatePaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failed': {
      id: '/failed'
      path: '/failed'
      fullPath: '/failed'
      preLoaderRoute: typeof FailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-payment': {
      id: '/api/public/create-payment'
      path: '/api/public/create-payment'
      fullPath: '/api/public/create-payment'
      preLoaderRoute: typeof ApiPublicCreatePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  FailedRoute: FailedRoute,
  SuccessRoute: SuccessRoute,
  ApiPublicCreatePaymentRoute: ApiPublicCreatePaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
